### ISSUE TITLE
vCal/iCal integration

### ISSUE THREAD

**Issue by brianray** [brianray/Chipy#15] opened 2011-07-27 13:04 UTC
vCal/iCal integration

**Comment by codersquid** [comment] 2011-07-27 14:07
This looks like a duplicate of #4.

**Comment by alesage** [comment] 2011-08-13 00:11
I'm going to close that one as this is more relevant to the now :) .

**Comment by paaschpa** [comment] 2012-05-01 22:12
- need vObject library
- added method to Meeting view named 'download_calendar' that will download a .ics file

**Closed as completed by paaschpa** 2012-05-01 22:12 UTC
